apiVersion: v1
kind: List
metadata: {}
items:
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    labels:
      app: user-mgmt-service
    name: user-mgmt-service
    namespace: dlu
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: 'user-mgmt-service:latest'
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        uri: 'https://github.com/DayongLu/user-mgmt-service.git'
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: 'springboot-maven3-centos:latest'
      type: Source
    successfulBuildsHistoryLimit: 5
    triggers:
    - github:
        secret: '-bQnWBPfSehj73jpuwSC'
      type: GitHub
    - generic:
        secret: mlt48zIoqCdRUUKqyvK-
      type: Generic
    - type: ConfigChange
    - imageChange:
        lastTriggeredImageID: >-
          codecentric/springboot-maven3-centos@sha256:91ecee201c42cfde8616dfe7b5c77c4f6100f95f50c6e8ffe16a78c99dde59bf
      type: ImageChange
  status:
    lastVersion: 1

- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      pipeline.alpha.openshift.io/uses: '[{"name": "user-mgmt-service", "namespace": "dlu", "kind": "DeploymentConfig"}]'
    name: user-mgmt-service-pipeline
  spec:
    source:
      git:
        ref: master
        uri: https://github.com/DayongLu/user-mgmt-service.git
      type: Git
    strategy:
      type: JenkinsPipeline
      jenkinsPipelineStrategy:
        jenkinsfilePath: Jenkinsfile
    triggers:
#    - generic:
#        secret: FiArdDBH
#      type: Generic