apiVersion: v1
kind: List
metadata: {}
items:

- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: user-mgmt-service
    labels:
      application: user-mgmt-service
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: user-mgmt-service:latest
    source:
      git:
        ref: "master"
        uri: ${GIT_URI}
      type: Git
    strategy:
      sourceStrategy:
        env:
        - name: SPRING_APPLICATION_NAME
          value: ${SPRING_APPLICATION_NAME}
        - name: SPRING_CLOUD_CONFIG_URI
          value: "http://demo-cs-as-config-server.middleware.svc.cluster.local:8888"
        - name: SPRING_PROFILES_ACTIVE
          value: "build"
        from:
          kind: ImageStreamTag
          name: redhat-openjdk18-openshift:1.1
          namespace: ${IMAGE_STREAM_NAMESPACE}
      type: Source
    triggers:
    - type: ConfigChange
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      pipeline.alpha.openshift.io/uses: '[{"name": "user-mgmt-service", "namespace": "dlu", "kind": "DeploymentConfig"}]'
    name: user-mgmt-service-pipeline
  spec:
    source:
      git:
        ref: master
        uri: https://github.com/DayongLu/user-mgmt-service.git
      type: Git
    strategy:
      type: JenkinsPipeline
      jenkinsPipelineStrategy:
        jenkinsfilePath: Jenkinsfile
    triggers:
#    - generic:
#        secret: FiArdDBH
#      type: Generic