apiVersion: v1
kind: List
metadata: {}
items:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      pipeline.alpha.openshift.io/uses: '[{"name": "user-mgmt-service", "namespace": "dlu", "kind": "DeploymentConfig"}]'
    name: user-mgmt-service-pipeline
  spec:
    source:
      git:
        ref: master
        uri: https://github.com/DayongLu/user-mgmt-service.git
      type: Git
    strategy:
      type: JenkinsPipeline
      jenkinsPipelineStrategy:
        jenkinsfilePath: Jenkinsfile
    triggers:
#    - generic:
#        secret: FiArdDBH
#      type: Generic