apiVersion: v1
kind: Template
metadata:
  annotations:
    iconClass: icon-java
  name: user-mgmt-service
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: user-mgmt-service
    labels:
      application: user-mgmt-service
  spec:
    tags:
    - name: latest
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: user-mgmt-service
    labels:
      application: user-mgmt-service
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: user-mgmt-service:latest
    source:
      git:
        ref: "master"
        uri: ${GIT_URI}
      type: Git
    strategy:
      sourceStrategy:
        env:
        - name: SPRING_APPLICATION_NAME
          value: ${SPRING_APPLICATION_NAME}
        - name: SPRING_CLOUD_CONFIG_URI
          value: "http://demo-cs-as-config-server.middleware.svc.cluster.local:8888"
        - name: SPRING_PROFILES_ACTIVE
          value: "build"
        from:
          kind: ImageStreamTag
          name: redhat-openjdk18-openshift:1.1
          namespace: ${IMAGE_STREAM_NAMESPACE}
      type: Source
    triggers:
    - type: ConfigChange
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: user-mgmt-service
    labels:
      app: user-mgmt-service
  spec:
    replicas: 1
    selector:
      deploymentconfig: user-mgmt-service
    strategy:
      resources: {}
      type: Recreate
    template:
      metadata:
        labels:
          app: user-mgmt-service
          deploymentconfig: user-mgmt-service
        name: user-mgmt-service
      spec:
        containers:
        - env:
          - name: SPRING_APPLICATION_NAME
            value: ${SPRING_APPLICATION_NAME}
          - name: SPRING_CLOUD_CONFIG_URI
            value: "http://demo-cs-as-config-server.middleware.svc.cluster.local:8888"
          - name: SPRING_PROFILES_ACTIVE
            value: ${SPRING_PROFILES_ACTIVE}
          image: cart
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          name: user-mgmt-service
          ports:
          - containerPort: 8080
            name: restapi
            protocol: TCP
          readinessProbe:
            failureThreshold: 10
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              memory: 1Gi
              cpu: 1
            requests:
              memory: 512Mi
              cpu: 200m
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 75
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - user-mgmt-service
        from:
          kind: ImageStreamTag
          name: user-mgmt-service:latest
      type: ImageChange
    - type: ConfigChange
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: user-mgmt-service
      application: user-mgmt-service
    name: user-mgmt-service
  spec:
    ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      name: restapi
    selector:
      deploymentconfig: user-mgmt-service
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      application: user-mgmt-service
    name: user-mgmt-service
  spec:
    to:
      kind: Service
      name: user-mgmt-service
      weight: 100
parameters:
- displayName: Application name
  name: APPLICATION_NAME
  required: true
  value: user-mgmt-service
- displayName: Profile Name
  name: SPRING_PROFILES_ACTIVE
  required: true
  value: test
- description: Git source URI for application
  displayName: Git source repository
  name: GIT_URI
  required: true
  value: https://github.com/DayongLu/user-mgmt-service.git
- description: Git branch/tag reference
  displayName: Git branch/tag reference
  name: GIT_REF
  value: master
- description: Define application name which will be used for Eureka service and config server
  displayName: Application Name
  name: SPRING_APPLICATION_NAME
- displayName: ImageStream Namespace
  description: Namespace in which the ImageStreams for Red Hat OpenJDK image is installed. These ImageStreams are normally installed in the openshift namespace. You should only need to modify this if you've installed the ImageStreams in a different namespace/project.
  name: IMAGE_STREAM_NAMESPACE
  required: true
  value: openshift